version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sistem_manajemen_pengelolaan_zakat_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    container_name: sistem_manajemen_pengelolaan_zakat_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sistem_manajemen_pengelolaan_zakat
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret123
    volumes:
      - dbdata:/var/lib/mysql

networks:
  default:
    external: true
    name: local

volumes:
  dbdata:
